Repository cpplint/cpplint, pull requests merged in 2025-03, with the labels that each got.

#316 Fix typos discovered by codespell
  CHANGELOG.rst
  cpplint.py
  samples/boost-sample/include/boost/math/octonion.hpp
  samples/chromium-sample/src/chrome_content_renderer_client.cc
  samples/codelite-sample/src/pptable.cpp
  samples/protobuf-sample/src/descriptor_unittest.cc
  samples/v8-sample/src/interface-descriptors.h
Labels: enhancement

#349 CONTRIBUTING.rst: Default branch is develop, add pre-commit
  CONTRIBUTING.rst
Labels: docs

#352 cpplint_clitest.py: Remove unnecessary class
  cpplint_clitest.py
Labels: tests

#350 Fix test refactoring
  cpplint_clitest.py
  cpplint_unittest.py
Labels: tests
